### ISSUE TITLE
Search Engine Optimization

### ISSUE THREAD

**Issue by huhubun** [huhubun/BunBlog.UI#2]
- [x] homepage (blog post list)
- [x] blog post detail
- [ ] tag detail
- [ ] category detail
- [ ] page detail

**Comment by huhubun** [comment]
Only SSR?

--

根据蜘蛛的UA来决定返回什么内容应该不行，涉嫌欺骗搜索引擎，不可取  
难道只有服务器端渲染（SSR）这一种办法吗？

**Comment by huhubun** [comment]
如果不区分蜘蛛，每发布/修改一篇博文，都由另一个程序专门往 BunBlog.UI 的发布目录下生成一个 HTML 文件，`header` 中包含 `title`、`meta` ，博文正文放在 `<noscript>` 中。  
对于首页，考虑用这个程序读取真实的 html 文件，然后修改里面的内容（博文列表、分类等）。

相较于 SSR 的好处：
- 不需要动BunBlog.UI项目，一切在后端进行
- 不需要引入 node.js 服务器端

缺点（或者不明确的地方）：
- 发布/修改博文后，由 BunBlog.API 触发一个消息，新开发另一个程序消费该消息，生成或修改对应的 HTML 文件
   - 引入消息队列、新程序也会占用服务器资源
   - 新程序定时刷新？每隔1天或者1小时，根据数据库中博文的修改时间来决定更新哪些文章，这样就不需要消息队列了

**Comment by huhubun** [comment]
其实核心思路就是，搜索引擎的蜘蛛找到对应页面时，至少 `title`、`meta` 中的 `description` `keywords` 还有博文正文需要生成好即可。

**Comment by huhubun** [comment]
vue 官方 ssr 文档 https://ssr.vuejs.org/ 十分劝退，考虑再三，决定使用 nuxt 来做。还好现在没有开发多少前台内容（大部分是后台管理），有可能需要把这个项目拆分成 UI.Front 和 UI.Admin。  
UI.Front 做服务器端渲染，便于搜索引擎抓取，UI.Admin 仍然保持目前的样子，只做浏览器渲染。

**Comment by huhubun** [comment]
试了一下把/admin管理页面也搬到nuxt里，做成仅客户端渲染，效果不错，已经提交一部分到 UI.Front 项目中，全部整合之后，会把 UI.Front 项目的内容提交到这个项目里。

**Comment by huhubun** [comment]
SEO 优化通过使用 Nuxt.js 进行服务器端渲染实现。目前支持设置 title 和 description meta

**Comment by james-wangx** [comment]
最近想开发一个博客，在考虑 SEO 时也很纠结。看了你的博客，决定用 nuxt 开发前端。感谢分享👍。
